LSSTDESC/DC2-production

scripts/generateDc2InstCat.py
@danielsf For this, I copied the [`generateDc1InstCat.py`](https://github.com/LSSTDESC/SSim_DC1/blob/master/scripts/generateDc1InstCat.py) script from SSim_DC1 to this repo and just substituted the DESCQA-related code from your example script for the DC1 galaxy code (and omitted the AGN items).
=> phosim instcat generation script using descqa catalogs for galaxies

Documents/DC2_Plan/main.tex
This very small PR involves mild changes in section 3 of the DC2 planning document to properly indicate that some of the planned DC2 analyses listed as science drivers will have heavy involvement by more than one working group.  The relevant collaborations are (WL, TJP) and (LSS, TJP) and (WL, LSS, TJP) as indicated in the document.  This addresses the issue that TJP did not appear to be represented previously (whereas really it was implicitly there in some of the projects).
Flagging this to TJP conveners, @jablazek @elikrause @philbull
=> properly indicate involved working groups for a subset of projects

scripts/merge_tract_cat.py
Patches with no valid entries marked 'isPrimary' in ref_table
were returning _all_ ref_table entries.  This fixes that by
* Explicitly restricting ref_table to isPrimary
* Skipping patches that are empty lists.
=> Fix isPrimary bug for empty patches

Notebooks/README.rst
I _think_ this will fix the CIT failure on the Part III notebook.
=> Fixed whitespace parsing in Part III filenames

Notebooks/FoFCatalogMatching Histogram.ipynb
This PR adds cells to the FoF matching notebook that show how to cross-reference the truth catalog with the extra-galactic catalog.
=> match truth catalog to extragalactic catalog

Documents/DC2_Plan/main.tex
While I was playing with the DC2-production repo and the new DC2-analysis repo, I discovered that I had some uncommitted changes to the DC2 planning document from a while ago.  This PR is the result of my committing those changes on a branch.  At some point there had been a question of the WL group DC2 simulation needs, which were driving some of the design choices and validation criteria in DESCQA; this additional paragraph includes those needs as originally articulated by the WL group [here](https://docs.google.com/presentation/d/1xHtwdI3C9c1cobiDFjt4qeZB45ojHn1QSNBrg2Uzx68/edit?usp=sharing).  Obviously the point is not to influence DC2 design at this stage, but rather to properly document why certain things were considered high priority.
I don't think there are any surprises here, …
=> incorporate WL group simulation needs in DC2 planning document

scripts/convert_merged_tract_to_dpdd.py
https://github.com/LSSTDESC/DC2-production/issues/270
This PR brings two new command-line config options to `scripts/convert_merged_tract_to_dpdd.py`:
- `--parquet_engine`: Parquet engine to use. Available: fastparquet (default) or pyarrow.
- `--parquet_compression`: Compression algorithm to use. Available: gzip (default), snappy, lzo, uncompressed.
Manually. Files were generated with all possible options, and read.
Documentation of the file has been updated and extended.
=> Issue/270: HDF to Parquet conversion: add broader choice of engine and compression algorithm

scripts/merge_tract_cat.py
Files will now be named, e.g., 'object_tract_4850.hdf5'
instead of 'merged_tract_4850.hdf5'
=> Add --name option to merge_tract_cat.py.  Default to 'object_'

scripts/trim_tract_cat.py
This PR updates the `columns_to_keep` in the `trim_tract_cat.py` script. The hard-coded `columns_to_keep` is now removed, and is replaced by using the quantity modifiers defined in `GCRCatalogs.dc2_object.DC2ObjectCatalog`. 
We also created a dummy class `DummyDC2ObjectCatalog` to make the script more readable. 
This PR partly fixes #296 (as one still need to regenerate the trimmed files).
=> update `columns_to_keep` in `trim_tract_cat.py` (fixes #296)

scripts/trim_tract_cat.py
Attempt to make `trim_tract_cat.py` more robust and faster by:
- use the keys in hdf5 files directly
- reduce the number of opening `infile`
=> make trim_tract_cat.py more robust and faster

LICENSE, README.md
As discussed in #217, this PR adds the BSD 3-Clause License to this repo, and fixes #217.
=> Add LICENSE to this repo

scripts/README.md, scripts/trim_tract_cat.py
* Produce the trim versions of the Run 2.1i DR1 ('dr1b') Object Table files from the IN2P3 Science PIpelines processing, which already generates `object_tract_????.hdf5` files.
* There were some bug fixes along the way in preparing this
* There was one somewhat confounding UnicodeDecodingError for one patch.  This patch was just skipped.
* Add documentation to README.
=> Issues/355 - Produce trim versions of Run 2.1i DR1 Object Table

scripts/generate_object_catalog.py, scripts/make_object_catalog.py, scripts/merge_parquet_files.py
This PR adds a script to generate object catalog in parquet format. This new script is called `generate_object_catalog.py` and replaces the functionality of `merge_tract_cat.py`. 
This is now a draft PR. The function `merge_coadd_forced_src` has been tested, but the CLI interface has not been tested. Also, the magnitude extraction part still needs to be fixed. 
This PR will fix #342.
=> add script to generate object catalog in parquet format

scripts/merge_tract_cat.py
This minor change represents the actual code used to generate the HDF5 DPDD files for Run2.1i and Run2.1.1i.
=> capture minor change when using more recent versions of DMstack

scripts/make_metacal_catalog.py
Trying to rebase this branch to master I somehow deleted the entire conversation on adding a script to convert metacal patch catalogs to parquet :-/ 
This PR aims at adding a script equivalent to `make_object_catalog.py` but to generate metacal parquet files. @yymao suggested directly modifying `make_object_catalog.py` to optionally process the metacal catalogs, but while implementing it seemed a separate script made more sense, it would have otherwise required a lot of modifications to the object catalog scripts, which I didn't want to mess with.
Functionally, this `make_metacal_catalog.py` script can be called with the same command line as `make_object_catalog.py`, yielding similar output files, one per patch.
I'm assuming there is a subsequent merging step for the object catalog paquet …
=> Adds script to generate parquet metacal catalog

scripts/make_object_catalog.py, scripts/merge_parquet_files.py
Currently `make_object_catalog.py` would generate one parquet file for each patch to allow easy embarrassingly parallelization. After all the patches are process, one has to run `merge_parquet_files.py` to merge all patches in the same tract into one single parquet file. 
In `merge_parquet_files.py`, the merge is done by loading all parquet files into memory as pandas DataFrame, and then use `pd.concat` to join them. This is necessary because the columns in different patches are not necessarily in the same order. 
So why different patches do not have the columns in the same order? This is because different patches have different sets of available filters, and the current implementation appends the missing filters at the end of the columns. 
To address these issues, this PR makes two …
=> Ensure columns in merged_cat are in same order to take advantage of native merge

scripts/write_gcr_to_parquet.py
change write_gcr_to_parquet.py so that 2 arguments now obsolete to drive pyarrow are removed
=> update to recent pyarrow

scripts/make_metacal_catalog.py
As title. While it takes a bit of space, this will save us much trouble debugging.
=> Keep object ID and store tract/patch info for metacal parquet files

scripts/write_gcr_to_parquet.py
This PR rewrites the script `write_gcr_to_parquet.py` that takes a catalog in GCRCatalogs and writes it to a parquet file. 
The original script is not memory-efficient and does not utilize some native feature pyarrow (since at that time we were supporting both pyarrow and fastparquet). Now that we are settled with pyarrow, much of this script should be rewritten to make use of them. 
The PR also now allows users to specify  `config_overwrite` to be passed to GCRCatalogs. In particular, this enables users to load only one tract at a time. 
@johannct can you test this? I was able to use this new script to generate one tract of `dc2_object_run2.2i_dr3` using NERSC's jupyter notebook in just a few seconds. On your machine it might even works with all tracts at once. The call signature is …
=> Rewrite write_gcr_to_parquet.py

scripts/write_gcr_to_parquet.py
(Updated 6/25/2020): This PR adds several improvements to `write_gcr_to_parquet.py`. 
- Reduce the memory footprint of `write_gcr_to_parquet.py` by calling `close_all_file_handles` (if available in the reader) and delete unused references
- Always include `tract` and `patch` if available for "tract catalogs"
- Add a `partition` option to save each partition as a single file.
=> Improve write_gcr_to_parquet.py

scripts/write_gcr_to_parquet.py
This PR adds an `--healpix` option in `scripts/write_gcr_to_parquet.py` so that it is more convenient to use this script to convert cosmoDC2 to parquet. The option can be used as:
```base
python ~/desc/DC2-production/scripts/write_gcr_to_parquet.py cosmoDC2_v1.1.4_image --healpix=8786
```
As a test, I am generating a few healpix pixels in `/global/cscratch1/sd/yymao/desc/cosmodc2-parquet` on NERSC if anyone wants to take a look. (cc @JoanneBogart @plaszczy @cwwalter)
=> add healpix option in write_gcr_to_parquet.py (for converting cosmoDC2 to parquet)

scripts/merge_truth_per_tract.py, scripts/repartition_into_tracts.py, scripts/write_gcr_to_parquet.py
This PR enables three scripts to process multiple files at once:
- `scripts/repartition_into_tracts.py`: 
Multiple input files are processed in serial, significantly reducing the overhead of starting python and loading skymap. Note that for each file, multiple cores are already used in the calculation of tract and patch.
- `scripts/merge_truth_per_tract.py`:
Multiple input files can be processed in serial or parallel, depending on `--n-cores`.
- `scripts/write_gcr_to_parquet.py`:
Multiple input files are processed in serial, reducing the overhead of starting python and loading catalog metadata. Python multiprocess is not used here because some catalogs in GCRCatalogs are not pickleable.
I have already tested all three scripts.
=> Enable processing multiple files at once

scripts/write_gcr_to_parquet.py
This PR updates `write_gcr_to_parquet.py` to ensure the parquet schema is consistent across files  generated within one GCR catalog.
The issue is first noticed by @wmwv in https://github.com/LSSTDESC/gcr-catalogs/pull/515#issuecomment-744687756. The cause is that `get_quantites` returns a python dictionary. While a python dictionary is always ordered for Python 3.7+, the implementation of `get_quantites` does not make such assumption nor an effort to keep it ordered. Hence, the returned dictionary can have keys in different orders every time.
This PR made two changes to ensure schema consistency:
1. First, in `_chunk_data_generator` where an arrow table is created from the returned dictionary of `get_quantites`, we now iterate over sorted columns instead of dictionary keys. 
2. …
=> Ensure schema is consistent across files generated by write_gcr_to_parquet.py

scripts/README.md, scripts/README_write_gcr_to_parquet.md
@heather999 has asked me to update `scripts/README.md` but the content is somewhat outdated and the file also seems to more like a log than instructions. 
I hence created a new file `scripts/READMD_write_gcr_to_parquet.md` to document how to use `write_gcr_to_parquet.py`. The procedures listed in this new file are what I used to generate the public release DPDD catalog.
=> Add scripts/READMD_write_gcr_to_parquet.md

scripts/README_write_gcr_to_parquet.md
In `README_write_gcr_to_parquet.md` that I created earlier, I said that one can do `--output-filename=<prefix>` but it really should be `--output-filename=<prefix>.parquet` (unless one doesn't want the "parquet" extensions, of course). 
This PR fixes it.
=> README fix: --output-filename needs extension

scripts/README_merge_truth_per_tract.md
This PR adds a readme file documenting how to use `merge_truth_per_tract.py` to generate truth-match catalogs. Fixes #419
=> Create README for `merge_truth_per_tract.py`
