scripts/protoDC2/generateDc2InstCat.py
=> enable catalog generation for imsim

Documents/DC2_Plan/main.tex
Here's the DC2 Plan main.tex file, copied from overleaf: I'll use this PR to check that it does not over-write more recent changes made to the current version in GitHub...
=> Javi's validation tables

Documents/README.md, README.md
Looking to make it easier to find our documentation - I'll work up the main README as well, and then assign Katrin as reviewer.
=> Documents README with links to DC2 Plan and Run 1.1 Specs

workflows/phosimConfig/commands.txt
Add one line to the phoSim command file to disable PRNU:
pixelerror 0
=> Disable PRNU per issue #111

Documents/DC2_Plan/main.tex
modified:   main.tex
changed (qualified) the objectives a bit.
=> Evolved objectives in SN

config/prod_software_config.ini, workflows/phosimConfig/commands.txt
@katrinheitmann @TomGlanzman Here are my guesses at our planned configuration for Run1.2p.  Please have a look, make corrections, and loop in anyone else who should help specify the configurations.
=> Run1.2p configuration

Documents/README.md
=> Fixed a typo and two broken links on the Documents/README.md file.

Notebooks/DC2 Coadd Run1.1p GCR access -- Tutorial (part1).ipynb, Notebooks/cic.py
@EiffL I added the code to do counts-in-cells and also some code to create and show a color-color plot for stars.
=> Additions to tutorial

scripts/merge_tract_cat.py
@wmwv @yymao This is a very small PR that sets the number of patches for HSC. Unfortunately, the Butler doesn't let you query the number of patches, so you would have to dig into the repository tree to figure it out programmatically (and it quickly gets ugly when you have to handle different filter names).
We will have to regenerate the HDF5 for hsc with this new version of the script.
=> Fixes the number of patches for HSC

Notebooks/FoFCatalogMatching Histogram.ipynb
This PR updates the FoF matching notebook to address @djperrefort's review in #211. Fix #211.
=> update FoF matching notebook to address review

Notebooks/DC2_Coadd_Run1.1p_Butler_Access_HSC_selection.ipynb
@jchiang87 can you take a quick look at this PR.
Define a few more things based on beta tester feedback.
DRP->DM Science Pipeline
=> Respond to beta tester report: Expand acronyms and define more terms.

Notebooks/DC2 Coadd Run1.1p GCR tutorial -- Part II: Lensing Cuts.ipynb
This PR addresses the comments in #216
=> Addressed Chihway's and Rachel's comments

Notebooks/DC2 Coadd Run1.1p GCR tutorial -- Part I: GCR Access.ipynb
This PR tries to address the comments for the Notebook `DC2 Coadd Run1.1p GCR tutorial Part I: GCR Access.ipynb` from Chihway and others in #215
=> Addressed comments from Chang, Bogart and Mudur

Notebooks/DC2 Coadd Run1.1p GCR tutorial -- Part III: Guided Challenges.ipynb, Notebooks/assets/gcr_coadd_tutorial_part3.py
This PR turns removes/comment the code from cells in `DC2 Coadd Run1.1p GCR tutorial -- Part III: Guided Challenges.ipynb` and puts the solution in a hidden python script, so that people can fill in the blanks.
Notebook should still be able to run without errors but will not produce plots.
=> Improved challenge in gcr coadd tutorial

Notebooks/DC2 Coadd Run1.1p direct access -- color-color stellar locus.ipynb
I've addressed the comments from @patricialarsen, @sschmidt23 to improve the narrative explanations in the notebook.
I've removed the density estimation cell.
=> Address comments on color-color locus direct access

Notebooks/DC2_Postage_Stamps.ipynb
=> Add explanatory note to restart Python kernel to switch backends.

scripts/convert_merged_tract_to_dpdd.py
Prompted by @plaszczy's question, I updated `convert_merged_tract_to_dpdd.py` to accommodate the new object catalogs (1.2p/i). In particular, this PR:
- Merges the three functions `convert_all_to_dpdd`, `convert_tract_to_dpdd`, and `convert_cat_to_dpdd` into just one (`convert_cat_to_dpdd`).
- Makes a new option `reader_config_overwrite`, instead of hard coding it. 
- Reads in catalog config to get the file pattern, instead of hard coding it. 
- Generalizes the code so single-tract and all-tract workflows are the same.
- Uses `reader_config_overwrite` to set `use_cache`.
- Updates "coadd" -> "object".
- Ensures no repeated columns.
- Minor code style updates and typo fixes.
- [added 11/30] Add options to write out only specified format(s) [fixes #293]
=> improve convert_merged_tract_to_dpdd.py

scripts/make_object_catalog.py
=> too much love for DESC (bug fix #363)

scripts/make_object_catalog.py
This PR adds the `--filters` CLI option to `make_object_catalog.py` to support non-ugrizy filter sets. There are several way to specify this option: 
- `--filters=hsc`  (use the hsc preset)
- `--filters=chft`  (use the chft preset)
- `--filters=ugrizy`  (if all filters have single-character names)
- `--filters=u,g,r,i,z,y,w1,w2`  (comma-separated filter names)
This PR is to make @boutigny's hot fix in 585a1f2 an actual user option.
=> Add `--filters` CLI option to `make_object_catalog.py`

Notebooks/verify_merged_matched_truth_cat.ipynb
@JoanneBogart -- sorry, I just realized that when I merged #403, I haven't actually pushed my edits to the notebook. These edits address your comments in #403. Can you give it another quick look? Thanks!
=> Add more explanation to the validation notebook in #403

.github/ISSUE_TEMPLATE/dc2-data-release-checklist.md
Add a link and a section header for derived catalogs
=> a couple suggested updates
